Ej/navigation view
digidem/mapeo-desktop-shell pull request #36
Opened 2023-04-13 17:24 UTC by lightlii

closes https://github.com/digidem/mapeo-desktop-shell/issues/13

One thing to note is I've added a menu icon to navigate back to navigation screen to the common layout. It's a deviation from the design but we currently don't have a way to bail back to the navigation screen. I've added a tooltip that says `Exit testing and return to navigation` to clarify  that it's not part of the proposed design. Will write a note about it in slack too since maybe worth getting Sabella's opinion too. I suggest either way it's a useful feature for development that we can remove at a later stage...

![image](https://user-images.githubusercontent.com/32508751/231836993-8cfc3e3f-c20e-4750-ad09-8c0177b6fc12.png)

---
# Preview

![image](https://user-images.githubusercontent.com/32508751/231829851-eab5712e-1906-412a-a8a1-724963711717.png)

2023-04-18 20:58 UTC, ErikSin requested changes
thanks for the small PR! The `MigratingProject/index.tsx` file shouldn't be in here

2023-04-18 20:58 UTC, ErikSin commented on src/renderer/src/views/Migration/index.tsx
>            <Row justifyContent="space-between" alignItems="flex-start">
There is some akward spacing when the screen is a little smaller (but still desktop sized):

<img width="342" alt="image" src="https://user-images.githubusercontent.com/67773827/232900355-84fc76b1-72ef-43b2-ba7a-08ea88b3b5b0.png">

2023-04-18 20:58 UTC, ErikSin commented on src/renderer/src/layouts/default/index.tsx
> +        </Tooltip>
Can you confirm with Sabella before merging this in?

2023-04-18 20:58 UTC, ErikSin commented on src/renderer/src/layouts/default/index.tsx
> +  const handleOpen = () => {
nit: call `handleToolTipOpen` and `handleToolTipClose`

2023-04-18 20:58 UTC, ErikSin commented on src/renderer/src/views/MigratingProject/index.tsx
im not sure why this file is showing up. The easiest way to deal with this file it to copy and paste from develop as I think this is coming from a rebase.

2023-04-20 10:08 UTC, lightlii commented on src/renderer/src/layouts/default/index.tsx
> +        </Tooltip>
I think I can remove it because https://github.com/digidem/mapeo-desktop-shell/issues/24 replaces this from what I can tell

2023-04-20 10:10 UTC, lightlii commented on src/renderer/src/views/Migration/index.tsx
>            <Row justifyContent="space-between" alignItems="flex-start">
this is already resolved in a later branch I believe

2023-04-20 10:28 UTC, lightlii commented on src/renderer/src/views/MigratingProject/index.tsx
It's particularly weird as it's showing up as an addition, ie as if the file doesn't exist on develop. Can confirm it's in dev...

2023-04-20 10:28 UTC, lightlii commented on src/renderer/src/views/MigratingProject/index.tsx
looks like this is why https://stackoverflow.com/a/35203417/6028893

2023-04-20 11:52 UTC, merged