Ej/Enter project name view
digidem/mapeo-desktop-shell pull request #39
Opened 2023-04-18 12:48 UTC by lightlii

Adds final view to migration (_data is detected_ flow) 

closes https://github.com/digidem/mapeo-desktop-shell/issues/8

---

# Preview 
![image](https://user-images.githubusercontent.com/32508751/232777646-da52dcea-4219-479e-8085-53413ca2bb30.png)

![image](https://user-images.githubusercontent.com/32508751/232777737-2d661f7f-e707-4e06-87e5-0df1a172502d.png)

2023-04-18 21:08 UTC, ErikSin requested changes
5 file, new record! Thanks for keeping it scoped :)

2023-04-18 21:08 UTC, ErikSin commented on src/renderer/src/views/MigrationComplete/index.tsx
> +import { Link } from 'react-router-dom'
Can get rid off `Link`

2023-04-18 21:08 UTC, ErikSin commented on src/renderer/src/views/MigratingProject/index.tsx
I can't access this file right now. Once you merge your other PR and rebase this, I can re-review

2023-04-24 18:29 UTC, ErikSin commented
Can you take a look at this again? There are some weird formatting thing happening, probably from the merge/rebase.

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/67773827/234084433-9d7b591e-4233-4460-abc7-0ba83a3f2f33.png">

2023-04-25 13:54 UTC, lightlii commented
that should be fixed now @ErikSin

2023-04-25 20:41 UTC, ErikSin approved these changes

2023-04-25 20:41 UTC, merged